#!/usr/bin/env bash
# WINDOWS leg — repackage the official windows.php.net NTS build (DLL-based).
#
# Windows does NOT use static-php-cli. A static Windows php.exe can neither load
# dynamic extensions (so yerd-php-ext's yerd-dump.dll could never load) nor link
# libpq (so pgsql is impossible). Like Laravel Herd, yerd therefore ships the
# official non-thread-safe (NTS) x64 build: php.exe + php-cgi.exe + php8.dll +
# ext/*.dll + support DLLs (libpq, openssl, ...), enabled via a generated yerd
# php.ini. This keeps pgsql, gives real dynamic-extension loading, and drops the
# c-ares problem entirely (the official Windows curl has no c-ares — verified by
# the §5 gate). The single-static-file §1 contract is intentionally relaxed for
# windows only: the artifact is a directory bundle, not one file.
#
# usage: repackage-windows.sh <php-version> <arch> <out-dir>
#   <php-version>  full x.y.z (e.g. 8.4.24)
#   <arch>         x86_64 (windows is x86_64-only)
#   <out-dir>      prepared tree is written to <out-dir>/php/
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "$here/config.sh"

VER="${1:?usage: repackage-windows.sh <php-version> <arch> <out-dir>}"
ARCH="${2:?arch}"
OUT="${3:?out-dir}"
[ "$ARCH" = "x86_64" ] || { echo "FATAL: windows is x86_64-only (got '$ARCH')"; exit 1; }

MINOR="${VER%.*}"
# windows.php.net tags each build with the VS toolset it was compiled with. PHP
# switched to VS17 (VS2022) at 8.4 and to VS16 (VS2019) at 8.0; 7.x is VC15
# (VS2017). This covers the stable (8.2-8.5) and legacy (7.4/8.0/8.1) minors.
case "$MINOR" in
  7.4)             VSTAG="vc15" ;;
  8.0|8.1|8.2|8.3) VSTAG="vs16" ;;
  8.4|8.5)         VSTAG="vs17" ;;
  *) echo "FATAL: no known VS toolset tag for PHP $MINOR on windows (add it)"; exit 1 ;;
esac

ZIPNAME="php-${VER}-nts-Win32-${VSTAG}-x64.zip"
BASE="https://windows.php.net/downloads/releases"           # core build (+ /archives)
PECL_BASE="https://windows.php.net/downloads/pecl/releases"  # PECL DLLs live here

# System32 first so `tar` is Windows bsdtar (extracts .zip and understands C:\ paths).
export PATH="/c/Windows/System32:$PATH"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
zip="$work/$ZIPNAME"

# Download from current releases/, falling back to archives/ for older patches.
# Prefer curl (CI Git Bash / macos / linux); fall back to PowerShell on a bare
# Windows box where MSYS has no curl.
fetch() {
  local url="$1" dst="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fSL --retry 3 "$url" -o "$dst"
  else
    powershell -NoProfile -Command "try { Invoke-WebRequest -Uri '$url' -OutFile '$dst' -ErrorAction Stop } catch { exit 22 }"
  fi
}
echo "repackage-windows: fetching $ZIPNAME"
if ! fetch "$BASE/$ZIPNAME" "$zip"; then
  echo "  not in releases/, trying archives/ ..."
  fetch "$BASE/archives/$ZIPNAME" "$zip" || { echo "FATAL: could not download $ZIPNAME from releases/ or archives/"; exit 1; }
fi
[ -s "$zip" ] || { echo "FATAL: downloaded $ZIPNAME is empty"; exit 1; }

# Extract (bsdtar handles zip). Prepared tree lives at $OUT/php.
dst="$OUT/php"
rm -rf "$dst"; mkdir -p "$dst"
tar -xf "$zip" -C "$dst"
[ -f "$dst/php.exe" ] && [ -f "$dst/php-cgi.exe" ] || { echo "FATAL: extracted build missing php.exe / php-cgi.exe"; exit 1; }

# Generate the yerd php.ini: enable every yerd stable extension that ships as an
# ext DLL in this build (built-ins like dom/phar/session need no line; PECL-only
# ones like redis/apcu are added by a later step). opcache is a zend_extension.
ini="$dst/php.ini"
{
  echo "; Generated by yerd-php repackage-windows.sh — do not edit by hand."
  echo "extension_dir = \"ext\""
} > "$ini"
# opcache is a separate php_opcache.dll on 8.2-8.4 (loaded as a zend_extension),
# but is compiled into php8.dll on 8.5 (no DLL, already loaded). Only emit the
# line when the DLL is actually present: loading a missing one prints a startup
# warning to stdout that corrupts the verify gate's captures.
if [ -f "$dst/ext/php_opcache.dll" ]; then
  echo "zend_extension=opcache" >> "$ini"
fi
enabled=0
for tok in ${STABLE_EXTENSIONS//,/ }; do
  case "$tok" in opcache|mbregex) continue ;; esac      # opcache handled above; mbregex is folded into mbstring
  if [ -f "$dst/ext/php_${tok}.dll" ]; then
    echo "extension=${tok}" >> "$ini"
    enabled=$((enabled+1))
  elif [ "$tok" = "gd" ] && [ -f "$dst/ext/php_gd2.dll" ]; then
    # PHP 7.x ships gd as php_gd2.dll; it was renamed to php_gd.dll in 8.0.
    echo "extension=php_gd2.dll" >> "$ini"
    enabled=$((enabled+1))
  fi
done
echo "repackage-windows: enabled $enabled bundled extensions in php.ini"

# PECL extensions (redis, apcu, serializers) — not in the official bundle. Fetch
# the prebuilt NTS x64 DLL per pin and drop it into ext/. Best-effort: a pin with
# no Windows DLL for this (minor, vs-tag) is a loud WARN, not a failure — the core
# bundle above is already complete and valid.
pecl_added=0; pecl_skipped=""
for spec in $WINDOWS_PECL; do
  pe="${spec%%:*}"; pv="${spec##*:}"
  purl="$PECL_BASE/$pe/$pv/php_${pe}-${pv}-${MINOR}-nts-${VSTAG}-x64.zip"
  pzip="$work/pecl-$pe.zip"; ptmp="$work/pecl-$pe"
  if fetch "$purl" "$pzip" >/dev/null 2>&1 && [ -s "$pzip" ]; then
    rm -rf "$ptmp"; mkdir -p "$ptmp"; tar -xf "$pzip" -C "$ptmp" 2>/dev/null || true
    # bash glob, NOT `find` — System32 is first on PATH (for bsdtar) and its
    # find.exe would shadow the Unix find. PECL zips put the DLL at the root.
    dll=""
    for cand in "$ptmp/php_${pe}.dll" "$ptmp"/*/"php_${pe}.dll"; do
      [ -f "$cand" ] && { dll="$cand"; break; }
    done
    if [ -n "$dll" ]; then
      cp "$dll" "$dst/ext/php_${pe}.dll"
      echo "extension=${pe}" >> "$ini"
      pecl_added=$((pecl_added+1))
    else
      pecl_skipped="$pecl_skipped ${pe}(no-dll-in-zip)"
    fi
  else
    pecl_skipped="$pecl_skipped ${pe}@${pv}(no build for ${MINOR}/${VSTAG})"
  fi
done
echo "repackage-windows: added $pecl_added PECL extensions"
[ -n "$pecl_skipped" ] && echo "repackage-windows: WARNING — PECL extensions not added:$pecl_skipped" >&2

# imagick — special-cased because its zip carries php_imagick.dll AND ImageMagick's
# runtime DLLs. php_imagick.dll goes in ext/; the CORE_RL_*/IM_MOD_RL_*/FILTER_*
# DLLs go in the bundle ROOT next to php.exe, since the loader resolves a loaded
# DLL's dependencies from the exe dir, not from ext/. .pdb symbols are skipped.
if [ -n "${WINDOWS_IMAGICK:-}" ]; then
  iurl="$PECL_BASE/imagick/$WINDOWS_IMAGICK/php_imagick-${WINDOWS_IMAGICK}-${MINOR}-nts-${VSTAG}-x64.zip"
  izip="$work/imagick.zip"; itmp="$work/imagick"
  if fetch "$iurl" "$izip" >/dev/null 2>&1 && [ -s "$izip" ]; then
    rm -rf "$itmp"; mkdir -p "$itmp"; tar -xf "$izip" -C "$itmp" 2>/dev/null || true
    if [ -f "$itmp/php_imagick.dll" ]; then
      cp "$itmp/php_imagick.dll" "$dst/ext/php_imagick.dll"
      for g in "CORE_RL_" "IM_MOD_RL_" "FILTER_"; do
        for f in "$itmp/${g}"*.dll; do [ -f "$f" ] && cp "$f" "$dst/"; done
      done
      echo "extension=imagick" >> "$ini"
      immct=0; for f in "$dst"/CORE_RL_*.dll "$dst"/IM_MOD_RL_*.dll "$dst"/FILTER_*.dll; do [ -f "$f" ] && immct=$((immct+1)); done
      echo "repackage-windows: added imagick $WINDOWS_IMAGICK (+ $immct ImageMagick runtime DLLs)"
    else
      echo "repackage-windows: WARNING — imagick zip had no php_imagick.dll" >&2
    fi
  else
    echo "repackage-windows: WARNING — imagick ${WINDOWS_IMAGICK} not available for ${MINOR}/${VSTAG}" >&2
  fi
fi

# The official build ships NO CA bundle, so curl/openssl can't verify TLS chains
# out of the box. Bundle the current cacert.pem. NOTE: unlike extension_dir (which
# PHP resolves relative to php.exe, so "ext" is relocatable), curl.cainfo /
# openssl.cafile are resolved relative to CWD — a relative value is unreliable for
# a FastCGI worker. So we ship the file + a commented template and leave the daemon
# to write the ABSOLUTE extracted path at install (a windows coordination point).
fetch "https://curl.se/ca/cacert.pem" "$dst/cacert.pem" || { echo "FATAL: could not download cacert.pem"; exit 1; }
{
  echo ""
  echo "; TLS CA bundle (shipped as cacert.pem next to php.exe). The daemon MUST set"
  echo "; these to the ABSOLUTE extracted path at install — PHP resolves them relative"
  echo "; to CWD, not php.exe, so a relative value would break under FastCGI:"
  echo ";curl.cainfo = \"C:\\\\absolute\\\\path\\\\to\\\\php\\\\cacert.pem\""
  echo ";openssl.cafile = \"C:\\\\absolute\\\\path\\\\to\\\\php\\\\cacert.pem\""
} >> "$ini"

echo "repackage-windows: $VER $ARCH prepared -> $dst"
